# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/document_prediction"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/image_prediction"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/image_segmentation"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/multimodal_prediction"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/object_detection"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/semantic_matching"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/tabular"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/text_prediction"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/projects/timeseries"
    schedule:
      interval: weekly
